# Generated by Django 3.1.7 on 2021-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phoneno',
            field=models.CharField(default='9876543210', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='Price Per kg', max_length=200),
        ),
    ]
